name: Linux
on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  linux:
    strategy:
      matrix:
        toolchain: [stable]
        type: [release]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{matrix.toolchain}}
          override: true

      - uses: actions/cache@v2
        with:
          path: |
            target
          key: linux-${{github.ref}}-${{github.sha}}
          restore-keys: |
            linux-${{github.ref}}-${{github.sha}}

      - name: Update packages
        run: sudo apt-get update;

      - name: Build Release
        run: cargo build --release --bin voidrat
        env:
          CARGO_INCREMENTAL: 0
          RUSTFLAGS: "-C debuginfo=0 -D warnings"
        if: ${{matrix.type == 'release'}}

      - name: Store Linux release
        uses: actions/upload-artifact@v2
        with:
          name: voidrat-${{runner.os}}-${{matrix.toolchain}}
          path: target/release/voidrat
        if: ${{matrix.type == 'release'}}
