name: Windows
on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  windows:
    strategy:
      matrix:
        toolchain: [stable]
        type: [release]
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{matrix.toolchain}}
          override: true

      - uses: actions/cache@v2
        with:
          path: |
            target
          key: windows-${{github.ref}}-${{github.sha}}
          restore-keys: |
            windows-${{github.ref}}-${{github.sha}}

      - name: Build
        run: cargo build --release
        env:
          CARGO_INCREMENTAL: 0
          RUSTFLAGS: "-C debuginfo=0 -D warnings"
        if: ${{matrix.type == 'release'}}

      - name: Store Windows release
        uses: actions/upload-artifact@v2
        with:
          name: voidrat-Windows-${{matrix.toolchain}}
          path: target/release/voidrat.exe
        if: ${{matrix.type == 'release'}}
